version: "3"
services:
  oeffimonitor:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/oeffimonitor
    environment:
      - NODE_ENV=production
      - DEBUG=*:*
    volumes:
      - ./:/home/node/oeffimonitor
    ports:
        - "8080:8080"
    command: "/usr/local/bin/node server/httpd.js"
    restart: on-failure
